This is makeindex, version 2.16 [MiKTeX 24.12].
Scanning style file ./document.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file document.acn....done (135 entries accepted, 0 rejected).
Sorting entries....done (998 comparisons).
Generating output file document.acr....done (84 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
